# Generated by Django 4.2.7 on 2025-10-31 19:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=255, verbose_name='Місто відправлення')),
                ('origin_country', models.CharField(max_length=100, verbose_name='Країна відправлення')),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта відправлення')),
                ('origin_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Довгота відправлення')),
                ('destination_city', models.CharField(max_length=255, verbose_name='Місто призначення')),
                ('destination_country', models.CharField(max_length=100, verbose_name='Країна призначення')),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта призначення')),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Довгота призначення')),
                ('cargo_type', models.CharField(max_length=255, verbose_name='Тип вантажу')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вага (кг)')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Об'єм (м³)")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('pickup_date', models.DateTimeField(verbose_name='Дата забору')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата доставки')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('in_transit', 'В дорозі'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('carrier', models.ForeignKey(blank=True, limit_choices_to={'role': 'carrier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL, verbose_name='Перевізник')),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255, verbose_name='Поточна локація')),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Поточна широта')),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Поточна довгота')),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Прогрес (%)')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='logistics.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Відстеження',
                'verbose_name_plural': 'Відстеження',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Запропонована ціна')),
                ('estimated_delivery', models.DateTimeField(verbose_name='Орієнтовна доставка')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Прийнято')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('carrier', models.ForeignKey(limit_choices_to={'role': 'carrier'}, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Перевізник')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='logistics.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-created_at'],
                'unique_together': {('route', 'carrier')},
            },
        ),
    ]
