# Generated by Django 4.2.7 on 2025-11-01 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='current_location',
            field=models.CharField(default='', max_length=255, verbose_name='Поточна локація'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='logistics.route', verbose_name='Маршрут')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
            ],
            options={
                'verbose_name': 'Повідомлення чату',
                'verbose_name_plural': 'Повідомлення чатів',
                'ordering': ['created_at'],
            },
        ),
    ]
