# Generated by Django 4.2.7 on 2025-11-01 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_tracking_current_location_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='progress_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогрес (%)'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
