# Generated by Django 4.2.7 on 2025-11-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_bid', 'Нова ставка'), ('bid_accepted', 'Вашу ставку прийнято'), ('bid_rejected', 'Вашу ставку відхилено'), ('new_message', 'Нове повідомлення'), ('route_assigned', 'Вам призначено маршрут'), ('route_completed', 'Маршрут завершено'), ('tracking_updated', 'Оновлено відстеження'), ('route_expired', 'Маршрут просрочений')], max_length=20, verbose_name='Тип сповіщення'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('in_transit', 'В дорозі'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано'), ('expired', 'Просрочений')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
