# Generated by Django 4.2.7 on 2025-11-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_carrierprofile_license_plate_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierprofile',
            name='license_plate_country',
        ),
        migrations.RemoveField(
            model_name='carrierprofile',
            name='license_plate_number',
        ),
        migrations.AddField(
            model_name='carrierprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='carrierprofile',
            name='address_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта адреси'),
        ),
        migrations.AddField(
            model_name='carrierprofile',
            name='address_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота адреси'),
        ),
        migrations.AddField(
            model_name='carrierprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Опис вашого досвіду та послуг', verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='carrierprofile',
            name='license_country',
            field=models.CharField(default='UA', help_text='Код країни для номерного знаку', max_length=10, verbose_name='Країна номера'),
        ),
        migrations.AlterField(
            model_name='carrierprofile',
            name='vehicle_model',
            field=models.CharField(max_length=150, verbose_name='Модель машини'),
        ),
    ]
