# Generated by Django 4.2.7 on 2025-11-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_carrierprofile_license_plate_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта адреси'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота адреси'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адреса'),
        ),
    ]
