# Generated by Django 4.2.7 on 2025-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_address_coordinates_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота'),
        ),
    ]
