"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR is the project root directory
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Secret key is used for cryptographic signing - NEVER share this in production!
SECRET_KEY = 'django-insecure-pmeube#7m+19!8(gh2xd)o(0hn+@q-%tdtg^hu@g77rt-dx&*o'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True shows detailed error pages - set to False in production!
DEBUG = True

# ALLOWED_HOSTS: List of host/domain names that this Django site can serve
# Empty list = any host can access (only for development!)
ALLOWED_HOSTS = []


# Application definition
# INSTALLED_APPS: List of all Django applications that are enabled
INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',          # Admin interface
    'django.contrib.auth',           # Authentication system
    'django.contrib.contenttypes',   # Content type framework
    'django.contrib.sessions',       # Session framework
    'django.contrib.messages',       # Messaging framework
    'django.contrib.staticfiles',   # Static file handling
    
    # Third-party apps
    'crispy_forms',                  # Beautiful Django forms
    'crispy_bootstrap5',             # Bootstrap 5 theme for crispy forms
    
    # Our custom apps
    'accounts',                       # User accounts, registration, profiles
    'logistics',                     # Routes, bids, tracking, messages, ratings
    'dashboard',                     # Home page, statistics, history
]

# MIDDLEWARE: List of middleware classes that process requests/responses
# Order matters! They execute top-to-bottom on request, bottom-to-top on response
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # Security enhancements
    'django.contrib.sessions.middleware.SessionMiddleware',   # Session management
    'django.middleware.common.CommonMiddleware',               # Common processing
    'django.middleware.csrf.CsrfViewMiddleware',              # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware', # User authentication
    'django.contrib.messages.middleware.MessageMiddleware',   # Message framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]

# ROOT_URLCONF: Python path to main URL configuration
# This file contains all URL patterns for the project
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Currently using SQLite (good for development)
# For production, use PostgreSQL or MySQL

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite database engine
        'NAME': BASE_DIR / 'db.sqlite3',          # Path to database file
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL prefix for static files (when accessed via browser)
STATIC_URL = 'static/'
# Directory where static files are located (for development)
STATICFILES_DIRS = [BASE_DIR / 'static']
# Directory where collectstatic will put all static files (for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user-uploaded files like logos, images)
# URL prefix for media files
MEDIA_URL = 'media/'
# Directory where uploaded files are stored
MEDIA_ROOT = BASE_DIR / 'media'

# Crispy Forms configuration
# Use Bootstrap 5 styling for all forms
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Custom User Model
# Tell Django to use our custom User model instead of default one
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Language and Timezone
LANGUAGE_CODE = 'uk'

# Authentication URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
